#include "led.h"
uint8_t R1=0, R2=0, R3=0, R4=0;
//==============================
void segchar (uint8_t seg)
{
	switch(seg)
	{
		case 1:
			SA_RESET;SB_SET;SC_SET;SD_RESET;SE_RESET;SF_RESET;SG_RESET;SG2_RESET;SH_RESET;SJ_RESET;SK_SET;SL_RESET;SM_RESET;SN_RESET;
			break;
		case 2:
			SA_SET;SB_SET;SC_RESET;SD_SET;SE_SET;SF_RESET;SG_SET;SG2_SET;SH_RESET;SJ_RESET;SK_RESET;SL_RESET;SM_RESET;SN_RESET;
			break;
		case 3:
			SA_SET;SB_RESET;SC_RESET;SD_SET;SE_RESET;SF_RESET;SG_SET;SG2_RESET;SH_RESET;SJ_RESET;SK_SET;SL_RESET;SM_RESET;SN_SET;
			break;
		case 4:
			//SA_RESET;SB_SET;SC_SET;SD_RESET;SE_RESET;SF_RESET;SG_RESET;SG2_SET;SH_RESET;SJ_RESET;SK_SET;SL_RESET;SM_RESET;SN_RESET;
			SA_RESET;SB_SET;SC_SET;SD_RESET;SE_RESET;SF_SET;SG_SET;SG2_SET;SH_RESET;SJ_RESET;SK_RESET;SL_RESET;SM_RESET;SN_RESET;
			break;
		case 5:
			SA_SET;SB_RESET;SC_SET;SD_SET;SE_RESET;SF_SET;SG_SET;SG2_SET;SH_RESET;SJ_RESET;SK_RESET;SL_RESET;SM_RESET;SN_RESET;
			break;
		case 6:
			SA_SET;SB_RESET;SC_SET;SD_SET;SE_SET;SF_SET;SG_SET;SG2_SET;SH_RESET;SJ_RESET;SK_RESET;SL_RESET;SM_RESET;SN_RESET;
			break;
		case 7:
			SA_SET;SB_RESET;SC_RESET;SD_RESET;SE_RESET;SF_RESET;SG_RESET;SG2_RESET;SH_RESET;SJ_RESET;SK_SET;SL_SET;SM_RESET;SN_RESET;
			break;
		case 8:
			SA_SET;SB_SET;SC_SET;SD_SET;SE_SET;SF_SET;SG_SET;SG2_SET;SH_RESET;SJ_RESET;SK_RESET;SL_RESET;SM_RESET;SN_RESET;
			break;
		case 9:
			SA_SET;SB_SET;SC_SET;SD_SET;SE_RESET;SF_SET;SG_SET;SG2_SET;SH_RESET;SJ_RESET;SK_RESET;SL_RESET;SM_RESET;SN_RESET;
			break;
		case 0:
			SA_SET;SB_SET;SC_SET;SD_SET;SE_SET;SF_SET;SG_RESET;SG2_RESET;SH_RESET;SJ_RESET;SK_RESET;SL_RESET;SM_RESET;SN_RESET;
			break;
		case 'P':
			SA_SET;SB_SET;SG_RESET;SG2_RESET;SF_SET;SE_SET;SC_SET;SD_RESET;SH_RESET;SJ_RESET;SK_RESET;SL_RESET;SM_RESET;SN_RESET;
			break;
		case 'A':
			SA_SET;SB_SET;SF_SET;SE_SET;SC_SET;SG_SET;SG2_SET;SH_RESET;SJ_RESET;SK_RESET;SL_RESET;SM_RESET;SN_RESET;SD_RESET;
			break;
		case 'H':
			SF_SET;SE_SET;SD_SET;SC_SET;SB_SET;SM_SET;SJ_SET;SA_RESET;SH_RESET;SK_RESET;SL_RESET;SN_RESET;SG_RESET;SG2_RESET;
			break;
		case 'O':
			SF_SET;SE_SET;SD_SET;SC_SET;SB_SET;SA_SET;SJ_RESET;SH_RESET;SK_RESET;SL_RESET;SN_RESET;SG_RESET;SG2_RESET;
			break;
		case 'Z':
			SF_RESET;SE_RESET;SD_RESET;SC_RESET;SB_RESET;SM_SET;SJ_SET;SA_RESET;SH_SET;SK_SET;SL_SET;SN_SET;SG_RESET;SG2_RESET;
			break;
	}
}

void ledprint(char number)
{
	R1 = number%10;
	R2 = number%100/10;
	R3 = number%1000/100;
	R4 = number/1000;
}
